### ISSUE TITLE
有大量拼音不准，是不是解析搜狗词库出问题了？

### ISSUE THREAD

**Issue by jymr92** [AielloChan/macOSInputEnhancer#2]
![image](https://github.com/AielloChan/macOSInputEnhancer/assets/44893500/e6c8e57a-9c20-4ada-b7bf-194f644e0e97)

见图

**Comment by AielloChan** [comment]
@jymr92 是个 bug，已经修复。你需要拉一下 master 的代码，然后重新执行一下构建生成 plist。
